micronaut:
  application:
    name: stravaView
  server:
    port: 10052
    cors:
      enabled: true
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/public/**"
        paths: "classpath:public"

netty:
  default:
    allocator:
      max-order: 3

strava:
  storeUrl: ${STORE_URL:`http://localhost:10051/stravaStore`}