micronaut:
  application:
    name: stravaFetch
  server:
    port: 10050
    cors:
      enabled: true
netty:
  default:
    allocator:
      max-order: 3

strava:
  client-id:
  client-secret:
  refresh-token:
