datasources:
  default:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/db?autoReconnect=true
    username: stravastore
    password: stravastore
    dialect: MYSQL
    driverClassName: com.mysql.cj.jdbc.Driver
r2dbc:
  datasources:
    default:
      url: r2dbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/db?autoReconnect=true
      username: stravastore
      password: stravastore