micronaut:
  application:
    name: stravastore
  server:
    port: 10051

flyway:
  datasources:
    default:
      enabled: true

netty:
  default:
    allocator:
      max-order: 3

strava:
  maxPerPage: 30
  emptyDbMonths: 3

# consul does not work with serde right now, see - https://github.com/micronaut-projects/micronaut-discovery-client/issues/385
#consul:
#  client:
#    defaultZone: ${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}
#    registration:
#      enabled: false