micronaut:
  application:
    name: stravastore
  server:
    port: 10051

flyway:
  datasources:
    default:
      enabled: true
#consul:
#  client:
#    defaultZone: ${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}
#    registration:
#      enabled: false
netty:
  default:
    allocator:
      max-order: 3

strava:
  maxPerPage: 30
  emptyDbMonths: 3